### ISSUE TITLE
Problem with Puma configuration file - Chapter 7, sample_app_6th_ed - page 370

### ISSUE THREAD

**Issue by Temceo** [mhartl/sample_app_6th_ed#27]
I have encountered 2 problems when running rails s after saving the file below:

# Puma configuration file.
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
port        ENV.fetch("PORT") { 3001 }
environment ENV.fetch("RAILS_ENV") { ENV['RACK_ENV'] || "development" }
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }
preload_app!
plugin :tmp_restart

1. Error stating - [8620] ERROR: worker mode not supported on ruby on this platform.  I overcame this error by commenting out the line  - "workers ENV.fetch("WEB_CONCURRENCY") { 2 }"

2. I subsequently then get the following error message when I run rails s.  It will only work if I change the port number to 3001 - "Only one usage of each socket address (protocol/network address/port) is normally 
permitted. - bind(2) for "::1" port 3000 (Errno::EADDRINUSE)"

I have googled, but cannot find any satisfactory answers as to why this is happening.

The book was released in 2021, so I assume all the code is up to date.  Do you know what is causing this issue please?

I am using windows 10 and using gem 'puma', '~> 5.0'

**Comment by mhartl** [comment]
Thanks for the report. You are right that the code is up to date; in fact, it was most recently updated yesterday. I have also just confirmed that the application works as described on all the systems I have access to.

It looks like the issue you’re having might be related to using Windows, which unfortunately isn’t particularly well-supported by Ruby or Rails. The good news is that it is now possible to install a native Linux system on Windows itself. This setup, which should give rise to much more consistent results when following the *Ruby on Rails Tutorial*, is described in [Section 3.3: Windows](https://www.learnenough.com/dev-environment-tutorial#sec-windows) from [*Learn Enough Dev Environment to Be Dangerous*](https://www.learnenough.com/dev-environment-tutorial).

**Comment by Temceo** [comment]
Thank you
