### ISSUE TITLE
Session controller book error

### ISSUE THREAD

**Issue by eclectic-coding** [mhartl/sample_app_6th_ed#33]
Michael,
In the basic login chapter of the PDF book (published 01-31-21), the create action incorrectly logs in the user with `log_in @user` whoever this should be `log_in user`

Thanks for the great resource

**Comment by mhartl** [comment]
Thanks for reaching out and for the kind words. Could you indicate the specific code listing you believe is in error? The only appearance of `log_in @user` in the current version of Chapter 8 is in [Listing 8.32](https://www.learnenough.com/ruby-on-rails-6th-edition-tutorial/basic_login#code-login_upon_signup). In that context, I believe the use of `@user` is correct. Note in particular that Listing 8.32 is for the Users controller, not the Sessions controller. (The latter does use `log_in user` instead.)

**Comment by eclectic-coding** [comment]
Sorry... you are correct, I missed the switch in the listings from sessions to user controllers. 

I am rebuilding this app as a review and incorporating Bootstrap 5 and a few other features along the way just for a review, especially the testing part.
