### ISSUE TITLE
Navbar dropdown menu stopped working

### ISSUE THREAD

**Issue by alexsmartens** [mhartl/sample_app_6th_ed#41]
Hi Michael,
thanks for your book and the sample app!

I developed a twitter sample app while reading your book. Just checked my app and the `Account` dropdown menu stopped working. I cloned your app and it's not working too:[ Nothing happens when you click the `Account` button on the navigation bar. It seems like something is off with `bootstrap` or `jqueru`. There is a `not found resource` error in the console.

 `Account` button:
 ![Screen Shot 2021-07-18 at 6 46 06 PM](https://user-images.githubusercontent.com/26261714/126084626-02e5e21f-b010-4cb2-b18e-d73398a7aa29.png)

Console error:
![Screen Shot 2021-07-18 at 6 56 57 PM](https://user-images.githubusercontent.com/26261714/126084668-f26de8a2-28ae-48d3-93f7-2ebb793f7d61.png)

Hoping you could help to resolve the issue

**Comment by mhartl** [comment]
Thanks for your message and for the kind words. Unfortunately, I am unable to reproduce the issue you describe. I just cloned the repo into a new directory and followed the README’s instructions, and the results were exactly as expected in all the browsers I have access to. My only suggestion is to retrace your steps and try different browser/system combinations (e.g., the cloud IDE). Also, in case it’s not just a typo, be sure to use `jquery`, not `jqueru`.
