### ISSUE TITLE
Appending the readme to avoid precompilation issues 

### ISSUE THREAD

**Issue by alexsmartens** [mhartl/sample_app_6th_ed#42]
I followed the readme and bumped into this error:

```
Webpacker can't find application.js in /Users/alex/Projects/sample_app_6th_ed/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```

Precompiling the assets helped, so I think these line (or similar) needs to be added to the installation instructions:
```
rails assets:precompile
```

**Comment by mhartl** [comment]
As noted [here](https://github.com/mhartl/sample_app_6th_ed/issues/41#issuecomment-882749528), I just successfully completed a fresh installation from scratch by cloning the repo, and everything worked as expected. Sorry I can be of more help.
